### ISSUE TITLE
SagiriServerError: undefined (4)

### ISSUE THREAD

**Issue by ChinHongTan** [ClarityCafe/Sagiri#291]
**Please describe the problem you are having in as much detail as possible:**
I had used sagiri for my discord bot for a while and it worked perfectly. However, today it seems like some error had occured. Whenever I used it it will show the error 
```
SagiriServerError: undefined (4)
     at /app/node_modules/sagiri/dist/index.js:74:19
     at Generator.next (<anonymous>)
     at fulfilled (/app/node_modules/sagiri/dist/index.js:5:58)
     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
I am sure my code is correct and my api key is correct but I couldn't fix this error. It didn't provide me with much information so thats all I can tell here. Also, it seems like there is sagiri version 3.1.1 on npm, and when I try installing 3.1.1, it will show module not found error like below.
```
Error: Cannot find module 'caseless'
Require stack:
- /app/available_modules/1621173818000/sagiri/node_modules/bent/src/nodejs.js
- /app/available_modules/1621173818000/sagiri/dist/index.js
- /app/index.js
```
**Include a reproducible code sample here, if possible:**
```js

// Place your code here
const sagiri = require('sagiri');
let mySauce = sagiri('api_key_here');
mySauce("url", { results: 10})
.then(response => {
    console.log('request sucessful');
    if (response.length < 1) return message.channel.send("No image was found!");
});
```

**Further details:**
- version: 3.1.0 & 3.1.1
- Node.js version: 14.x (latest version of node 14)
- Operating system: heroku
- Priority this issue should have – please be realistic and elaborate if possible:

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by ChinHongTan** [comment]
ok nevermind for whatever reason it fixed itself
Maybe it's just Saucenao's server side problem
