### ISSUE TITLE
Example does not work with NodeJS

### ISSUE THREAD

**Issue by UiharuKazari2008** [ClarityCafe/Sagiri#609]
**Please describe the problem you are having in as much detail as possible:**

**Include a reproducible code sample here, if possible:**

```js
(async () => {
const sagiri = require("sagiri");

const client = sagiri("AKI_KEY");
const results = await client("https://media.737.jp.net/preview/716206086947864617/965828904629710878/5546499.jpg?version=1275092379942125670");
console.log(results)
})()
```

```shell
/usr/local/bin/node /Users/kazari/Library/Application Support/JetBrains/IntelliJIdea2023.1/scratches/scratch_8.js
/Users/kazari/IdeaProjects/sequenzia-framework/node_modules/sagiri/dist/sagiri.cjs:36
var nodeFetch = __toESM(require("node-fetch"), 1);
                        ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/kazari/IdeaProjects/sequenzia-framework/node_modules/sagiri/node_modules/node-fetch/src/index.js from /Users/kazari/IdeaProjects/sequenzia-framework/node_modules/sagiri/dist/sagiri.cjs not supported.
Instead change the require of index.js in /Users/kazari/IdeaProjects/sequenzia-framework/node_modules/sagiri/dist/sagiri.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/kazari/IdeaProjects/sequenzia-framework/node_modules/sagiri/dist/sagiri.cjs:36:25)
    at /Users/kazari/Library/Application Support/JetBrains/IntelliJIdea2023.1/scratches/scratch_8.js:2:16
    at Object.<anonymous> (/Users/kazari/Library/Application Support/JetBrains/IntelliJIdea2023.1/scratches/scratch_8.js:7:3) {
  code: 'ERR_REQUIRE_ESM'
}

Process finished with exit code 1
```

**Further details:**

- version: ^4.1.0
- Node.js version: v16.14.0
- Operating system: macOS 12.7.6 
- Priority this issue should have – please be realistic and elaborate if possible: Reporting but prob just writing my own library at this point

- [x] I have also tested the issue on latest master, commit hash:

**Comment by sr229** [comment]
Looks like there's a problem with how I implemented CJS versions of the library, does using ESM work?

**Comment by sr229** [comment]
This should be solved with v4.2.0, can you verify if this is the case @UiharuKazari2008 ?

**Comment by UiharuKazari2008** [comment]
Probably want to add that Node 20 is now a requirement sense 18.0 is still considered a LTS version 
```
~/IdeaProjects/sequenzia-web/public/static/vendor/jquery (prerelease ✘)✚✭ ᐅ npm i sagiri
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sagiri@4.2.0',
npm WARN EBADENGINE   required: { node: '20.x' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.3.1' }
npm WARN EBADENGINE }
npm notice 
npm notice New major version of npm available! 8.3.1 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice Run npm install -g npm@10.9.0 to update!
npm notice 
npm ERR! code 1
npm ERR! path /Users/kazari/IdeaProjects/sequenzia-web/public/node_modules/sagiri
npm ERR! command failed
npm ERR! command sh -c node scripts/postinstall.js
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module '/Users/kazari/IdeaProjects/sequenzia-web/public/node_modules/sagiri/scripts/postinstall.js'
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kazari/.npm/_logs/2024-10-09T20_48_26_591Z-debug-0.log
~/IdeaProjects/sequenzia-web/public/static/vendor/jquery (prerelease ✘)✚✭ ᐅ 
```
but post install fails
```
~/IdeaProjects/sequenzia-web (prerelease ✘)✚✭ ᐅ npm i sagiri
npm error code 1
npm error path /Users/kazari/IdeaProjects/sequenzia-web/node_modules/sagiri
npm error command failed
npm error command sh -c node scripts/postinstall.js
npm error node:internal/modules/cjs/loader:1228
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module '/Users/kazari/IdeaProjects/sequenzia-web/node_modules/sagiri/scripts/postinstall.js'
npm error     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
npm error     at Module._load (node:internal/modules/cjs/loader:1051:27)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
npm error     at node:internal/main/run_main_module:28:49 {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: []
npm error }
npm error
npm error Node.js v20.18.0
npm notice
npm notice New minor version of npm available! 10.8.2 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
npm error A complete log of this run can be found in: /Users/kazari/.npm/_logs/2024-10-09T21_45_36_881Z-debug-0.log
~/IdeaProjects/sequenzia-web (prerelease ✘)✚✭ ᐅ 
```

**Comment by sr229** [comment]
Sure thing, I'm just going to release a new patch to pin it to 20

**Comment by sr229** [comment]
Please try again with 4.2.1. It should just work now if you have Node.js 20+

**Comment by UiharuKazari2008** [comment]
sadly same error :(
```
~/IdeaProjects/sequenzia-web (prerelease ✘)✹✚✭ ᐅ npm i sagiri@4.2.1
npm error code 1
npm error path /Users/kazari/IdeaProjects/sequenzia-web/node_modules/sagiri
npm error command failed
npm error command sh -c node scripts/postinstall.js
npm error node:internal/modules/cjs/loader:1228
npm error   throw err;
npm error   ^
npm error
npm error Error: Cannot find module '/Users/kazari/IdeaProjects/sequenzia-web/node_modules/sagiri/scripts/postinstall.js'
npm error     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
npm error     at Module._load (node:internal/modules/cjs/loader:1051:27)
npm error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
npm error     at node:internal/main/run_main_module:28:49 {
npm error   code: 'MODULE_NOT_FOUND',
npm error   requireStack: []
npm error }
npm error
npm error Node.js v20.18.0
npm notice
npm notice New minor version of npm available! 10.8.2 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
npm error A complete log of this run can be found in: /Users/kazari/.npm/_logs/2024-10-10T00_10_11_775Z-debug-0.log
~/IdeaProjects/sequenzia-web (prerelease ✘)✹✚✭ ᐅ 
```

**Comment by sr229** [comment]
This is really weird because the CI should've been able to catch this... Let me try in runkit

**Comment by UiharuKazari2008** [comment]
Yep that works 
```
/usr/local/bin/node /Users/kazari/Library/Application Support/JetBrains/IntelliJIdea2023.1/scratches/scratch_12.js
Created sagiri instance with opts: {"results":5}
Searching for possible sources of image: https://media.737.jp.net/full/716206086947864617/716529641808199690/6270503.jpg?_=1293125110353367070
Exepcted 5 results, got 8, with saucenao reporting 8 results.
[
  {
    url: 'https://www.pixiv.net/member_illust.php?mode=medium&illust_id=16455739',
    site: 'Pixiv',
    index: 5,
    similarity: 34.8,
    thumbnail: 'https://img1.saucenao.com/res/pixiv/1645/manga/16455739_p8.jpg?auth=ulujFniylMNUrt8ye8o-PA&exp=1729018800',
    authorName: '白楠 月玻',
    authorUrl: 'https://www.pixiv.net/users/2508768',
    raw: { header: [Object], data: [Object] }
  },
  {
    url: 'https://www.pixiv.net/member_illust.php?mode=medium&illust_id=16455739',
    site: 'Pixiv',
    index: 5,
    similarity: 34.65,
    thumbnail: 'https://img1.saucenao.com/res/pixiv/1645/manga/16455739_p7.jpg?auth=nN0iF63gsubV3ecOCBhELw&exp=1729018800',
    authorName: '白楠 月玻',
    authorUrl: 'https://www.pixiv.net/users/2508768',
    raw: { header: [Object], data: [Object] }
  },
  {
    url: 'https://deviantart.com/view/988170993',
    site: 'deviantArt',
    index: 34,
    similarity: 33.42,
    thumbnail: 'https://img3.saucenao.com/dA2/98817/988170993.jpg?auth=9ytbEW5Gzh1YaKtQLeLuoQ&exp=1729018800',
    authorName: 'kittensurgery',
    authorUrl: 'https://www.deviantart.com/kittensurgery',
    raw: { header: [Object], data: [Object] }
  },
  {
    url: 'https://deviantart.com/view/966855783',
    site: 'deviantArt',
    index: 34,
    similarity: 32.51,
    thumbnail: 'https://img3.saucenao.com/dA2/96685/966855783.jpg?auth=izTOosqsSkR2HqOLUO0uIA&exp=1729018800',
    authorName: 'PerfectWaifus',
    authorUrl: 'https://www.deviantart.com/perfectwaifus',
    raw: { header: [Object], data: [Object] }
  },
  {
    url: 'https://deviantart.com/view/953473945',
    site: 'deviantArt',
    index: 34,
    similarity: 32.51,
    thumbnail: 'https://img3.saucenao.com/dA2/95347/953473945.jpg?auth=vurDwZIpvU00YOfdSldi4w&exp=1729018800',
    authorName: 'Burnsaigency',
    authorUrl: 'https://www.deviantart.com/burnsaigency',
    raw: { header: [Object], data: [Object] }
  },
  {
    url: 'https://deviantart.com/view/373515577',
    site: 'deviantArt',
    index: 34,
    similarity: 32.23,
    thumbnail: 'https://img3.saucenao.com/dA/37351/373515577.jpg?auth=Sv5cNHMHywkkTw_RQ__6Cw&exp=1729018800',
    authorName: 'Kinipharian',
    authorUrl: 'http://kinipharian.deviantart.com',
    raw: { header: [Object], data: [Object] }
  },
  {
    url: 'https://www.furaffinity.net/view/42265416',
    site: 'FurAffinity',
    index: 40,
    similarity: 32.01,
    thumbnail: 'https://img3.saucenao.com/furaffinity/4226/42265416.jpg?auth=WN_ry0nqdmAie19tCq3i9Q&exp=1729018800',
    authorName: 'Pornkitsi',
    authorUrl: 'https://www.furaffinity.net/user/pornkitsi',
    raw: { header: [Object], data: [Object] }
  },
  {
    url: 'https://deviantart.com/view/846379731',
    site: 'deviantArt',
    index: 34,
    similarity: 31.99,
    thumbnail: 'https://img3.saucenao.com/dA2/84637/846379731.jpg?auth=8-yuMN-Q35lJIrloExelbA&exp=1729018800',
    authorName: 'bean-io',
    authorUrl: 'https://www.deviantart.com/bean-io',
    raw: { header: [Object], data: [Object] }
  }
]
```
Now i can work on integrating this into my web app sense it works a lot better then what i was doing

**Comment by sr229** [comment]
Alrighty, thanks for reporting! I'll close this off now.
